name: nti_shopping_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  get_it: ^7.7.0
  injectable: ^2.5.0
  flutter_secure_storage: ^11.2.0
  google_fonts: ^8.2.1
  bloc: ^8.1.4
  meta: ^1.18.3
  http: ^1.6.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.6
  animate_do: ^5.1.0
  smooth_page_indicator: ^3.0.0
  flutter_svg: ^2.3.0
  skeletonizer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/